jwt:
  secret: ${JWT_KEY:ak02Qi9sRWZmVGM0TzR6VjNKOHBNSTVtckptOVhwWkZNUW5vSnFlOVFibGtiVXZObVhIRElEQ3RSZGxkVGE5eGdnTHlsZUVWazZ4ZXc5ZXdNVUVmOWc9PQ}
  expiration:
    ms:
      access: 86400000          # 1 day
      refresh: 604800000      # 7 days

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

server:
  port: 8080

spring:
  application:
    name: subscriptions-control

  banner:
    location: classpath:banner.txt

  datasource:
    url: jdbc:postgresql://localhost:5432/myapp
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
